cart_app/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('cart/', views.cart_detail,name='cart_detail'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('increment_item/<int:item_id>/', views.increment_item, name='increment_item'),
    path('decrement_item/<int:item_id>/', views.decrement_item, name='decrement_item'),
    path('delete_item/<int:item_id>/', views.delete_item, name='delete_item'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from productapp.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('allproducts/', include('productapp.urls')),
    path('search_app/', include('search_app.urls')),
    path('cart_app/', include('cart_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

productapp/urls.py
from django.urls import path
from .views import home, allproducts, product_detail

app_name = 'productapp'
urlpatterns = [
    path('allproducts/', allproducts, name='allproducts'),
    path('<slug:c_slug>/', allproducts, name='products_by_category'),
    path('product/<slug:product_slug>/', product_detail, name='product_detail'),
]

search_app/urls.py
from django.urls import path
from . import views

app_name = 'search_app'
urlpatterns = [
    path('search/', views.SearchResult, name='SearchResult'),
]

cart_app/models.py
from django.db import models
from productapp.models import Product

class Cart(models.Model):
    cart_id=models.CharField(max_length=250, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['created_at']

    def __str__(self):
        return '{}' .format(self.cart_id)

class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    active = models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price* self.quantity
    
    def __str__(self):
        return '{}' .format(self.product)

productapp/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('productapp:products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, blank=True, null=True)
    image = models.ImageField(upload_to='product', blank=True)
    stock=models.IntegerField(default=0)
    available=models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('name',)
        verbose_name='prodcut'
        verbose_name_plural='products'

    def __str__(self):
        return '{}'.format(self.name)

search_app/models.py
from django.db import models

# Create your models here.

cart_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Cart, CartItem 
from productapp.models import Product
from django.core.exceptions import ObjectDoesNotExist

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))

    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product, quantity=1, cart=cart)
        cart_item.save()

    return redirect('cart:cart_detail')

def increment_item(request, item_id):
    cart_item = get_object_or_404(CartItem, id=item_id)
    cart_item.quantity += 1
    cart_item.save()
    return redirect('cart:cart_detail')

def decrement_item(request, item_id):
    cart_item = get_object_or_404(CartItem, id=item_id)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def delete_item(request, item_id):
    cart_item = get_object_or_404(CartItem, id=item_id)
    cart_item.delete()
    return redirect('cart:cart_detail')

def cart_detail(request, total=0, counter=0,grant=50, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
            grant += total
    except ObjectDoesNotExist:
        pass
    
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total,grant=grant, counter=counter))

productapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Category, Product

def index(request):
    return HttpResponse("Welcome to New2U")

def home(request, c_slug=None):
    category = None
    products = None
    if c_slug:
        category = get_object_or_404(Category, slug=c_slug)
        products = Product.objects.filter(category=category, available=True)
    else:
        products = Product.objects.filter(available=True)
    
    context = {
        'category': category,
        'products': products,
    }
    context = {
        'category': category,
        'products': products,
    }
    return render(request, 'category.html', context)

def allproducts(request, c_slug=None):
    category = None
    products = None
    if c_slug:
        category = get_object_or_404(Category, slug=c_slug)
        products = Product.objects.filter(category=category, available=True)
    else:
        products = Product.objects.filter(available=True)
    
    context = {
        'category': category,
        'products': products,
    }

    return render(request, 'category.html', context)

def product_detail(request, product_slug):
    product = get_object_or_404(Product, slug=product_slug)
    
    context = {
        'product': product,
    }

    return render(request, 'product_details.html', context)

search_app/views.py
from django.shortcuts import render
from productapp.models import Product
from django.db.models import Q

def SearchResult(request):
    query = request.GET.get('q')
    if query:
        results = Product.objects.filter(name__icontains=query)
    else:
        results = None

    context = {
        'query': query,
        'results': results,
    }

    return render(request, 'search_results.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <div id="content">
        {% include 'header.html' %}
        {% include 'navbar.html' %}

        {% block content %}
        {% endblock %}

        {% include 'footer.html' %}
    </div>
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'css/styles2.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <title>New2U</title>
</head>
<body>
    <div class="cart-container">
        {% if cart_items %}
            <div style='display:flex;'>
                <div>
                    <table class="cart-table">
                        <thead>
                            <tr style='background-color: #efefef;'>
                                <td ></td>
                                <td>Product Image</td>
                                <td>Name</td>
                                <td>Price</td>
                                <td>Quantity</td>
                                <td>Total</td>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in cart_items %}
                                <tr>
                                    <td> 
                                        <a href="{% url 'cart:delete_item' item.id %}"><i class="far fa-window-close" style='color:black;'></i></a>
                                    </td>
                                    <td>
                                        <img src="{{ item.product.image.url }}" alt="{{ item.product.name }}" class="product-image">
                                    </td>
                                    <td>
                                        {{ item.product.name }}
                                    </td>
                                    <td>
                                        ₹{{ item.product.price }}
                                    </td>
                                    <td style="display: flex; align-items: center; border-bottom: none; ">
                                        <form method="post" action="{% url 'cart:decrement_item' item.id %}">
                                            {% csrf_token %}
                                            <button type="submit" class="arrow-btn increment-btn">&#9660;</button>
                                        </form>
                                        <span class="quantity">{{ item.quantity }}</span>
                                        <form method="post" action="{% url 'cart:increment_item' item.id %}">
                                            {% csrf_token %}
                                            <button type="submit" class="arrow-btn decrement-btn">&#9650;</button>
                                        </form>
                                    </td>
                                    <td>
                                        ₹{{ item.sub_total }}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div style='margin-left:50px;'>
                    <table class="cart-price-table">
                        <thead>
                            <tr style='background-color: #efefef;'>
                                <td>Total</td>
                                <td>Price</td>
                            </tr>
                        </thead>
                        <tr>
                            <td>
                                Subtotal:
                            </td>
                            <td> 
                                ₹{{ total }}
                            </td>
                        <tr>
                            <td>
                                Shipping:
                            </td>
                            <td>
                                ₹ 50
                            </td>
                        </tr>
                        <tr>
                            <td>
                                Total:
                            </td>
                            <td>
                                ₹{{grant}}
                            </td>
                        </tr>	
                    </table>
                    <div style='display:flex;'>
                        <button class='check-out-button'>Check Out</button>
                        <a href="{% url 'productapp:allproducts' %}" class='continue-shopping-button'>Continue Shopping</a>
                    </div>
                </div>
            </div>
        {% else %}
            <p class="empty-cart">Your cart is empty.</p>
        {% endif %}
    </div>
</body>
</html>
{% endblock %}

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/styles2.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>
<body>
    <div class="container">
        {% for product in products %}
            <div class="product-card">
                <div class='image-div'>
                    <img src="{{ product.image.url }}" alt="{{ product.name }}" clas='product-card-img'>
                </div>
                <a href="{% url 'productapp:product_detail' product_slug=product.slug %}">{{ product.name }}</a>
                <div class="product-card-price">₹{{ product.price }}</div>
                <button class='button-cart'><i class="fas fa-shopping-cart"></i> Add to cart </button>
            </div>
        {% endfor %}
    </div>
</body>
</html>
{% endblock %}

templates/footer.html
<footer class="footer mt-auto py-3">
    <div class="container text-center">
        <span class="text-muted">&copy; 2024 New2U Website</span>
    </div>
</footer>

templates/header.html
{% comment %} {% load static %}

<header>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h1>{% block header_title %}My E-Commerce Site{% endblock %}</h1>
                <img src='https://w7.pngwing.com/pngs/621/196/png-transparent-e-commerce-logo-logo-e-commerce-electronic-business-ecommerce-angle-text-service.png'>
            </div>
        </div>
    </div>
</header> {% endcomment %}

templates/navbar.html
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <title>New2U</title>
</head>
<body>
    <nav class='nav-bar'>
        <div class='logo'>
            <a href="{% url 'productapp:allproducts' %}"><img src="{% static "img/logo.png" %}" alt="Logo"></a>
            <a href="{% url 'productapp:allproducts' %}" id='logo'>New2U</a>
        </div>
        <div class='nav-link-div'>
            <div class="dropdown">
                <a class="nav-link">Products</a>
                <div class="dropdown-content">
                    {% for product in links %}
                        <a href="{{ product.get_url }}">{{ product.name }}</a>
                    {% endfor %}
                </div>
            </div>
            <a href="#" class="nav-link">Wishlist</a>
            <a href="#" class="nav-link">Orders</a>
            <a href="#" class="nav-link">Login</a>
        </div>

        <div class='search-cart'>
            <form action="{% url 'search_app:SearchResult' %}" method="get" class='nav-form'>
                {% csrf_token %}
                <input type="text" name="q" class="search-input" placeholder="Search...">
                <button type="submit" class="fas fa-search" style='border: none; background-color: transparent; color: white'></button>
            </form>
            &nbsp;&nbsp;&nbsp;&nbsp;
            {%if item_count %}
                <a href='{% url "cart:cart_detail" %}' style='color: white'>
                    <i class="fas fa-shopping-cart"></i> {{item_count}}
                </a>
            {% endif%}
        </div>
    </nav>
</body>
</html>

templates/product_details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles2.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <title>{{ product.name }} - Product Detail</title>
</head>
<body>
    <div class="product-detail-container">
        <div class="product-detail-image">
            <img src="{{ product.image.url }}" alt="{{ product.name }}">
        </div>
        <div class="product-detail-details">
            <h3>{{ product.name }}</h3> 
            <p class="product-detail-price">₹{{ product.price }}</p>
            <p class='product-detail-discription'>{{ product.description }}</p>
            <a href="{% url 'cart:add_cart' product_id=product.id %}" class='button-cart'>
                <i class="fas fa-shopping-cart"></i> Add to cart
            </a>
        </div>
    </div>
</body>
</html>
{% endblock %}

templates/search_results.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'css/styles2.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>
<body>
    <div>
        <h1>Showing results for "{{ query }}":</h1>
    </div>
    <div class="container">
        {% if results %}
            {% for product in results %}
            <div class="product-card">
                <div class='image-div'>
                    <img src="{{ product.image.url }}" alt="{{ product.name }}" clas='product-card-img'>
                </div>
                <a href="{% url 'productapp:product_detail' product_slug=product.slug %}">{{ product.name }}</a>
                <div class="product-card-price">₹{{ product.price }}</div>
                    <button class='button-cart'><i class="fas fa-shopping-cart"></i> Add to cart </button>
            </div>
            {% endfor %}
        {% else %}
            <p>No results found.</p>
        {% endif %}
    </div>
</body>
</html>
{% endblock %}

templates/trial.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Your existing head content... -->

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/styles2.css' %}">
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }

        #header {
            background-color: #333;
            padding: 15px;
            text-align: center;
            color: white;
        }

        #main-content {
            margin: 20px;
            display: flex;
            flex-wrap: wrap;
            justify-content: space-around;
        }

        .product-card {
            background-color: red;
            border: 1px solid #ddd;
            border-radius: 10px;
            overflow: hidden;
            margin: 10px;
            width: 300px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .product-card a {
            text-decoration: none;
            color: #333;
            font-weight: bold;
            font-size: 18px;
            padding: 10px;
            display: block;
        }

        .product-card img {
            max-width: 100%;
            height: auto;
            border-bottom: 1px solid #ddd;
        }

        .product-card p {
            margin: 10px 0;
            color: #555;
            padding: 10px;
        }

        .product-card-price, .product-card-stock {
            font-size: 16px;
            color: #777;
            padding: 10px;
        }
    </style>
</head>
<body>

{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
        All Products
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
        {{ category.name }}
    {% else %}
        See Our New collection
    {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
        <div>
            <div>
                <a href="{% url 'productapp:allproducts' %}"> Our New Products</a>
            </div>
        </div>
        <div>
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVUO1IP1RqdKRHCV3Z7bBAE7DX0_4XgfW4fw&usqp=CAU">
            <br>
            <p> {{category.name}} </p>
            <br>
            <p> {{category.description}} </p>
            <h1>hii hello</h1>
        </div>
    {% else %}
        <div>
            
            <h1></h1>
        </div>
    {% endif %}

    {% for product in products %}
        <div class="product-card">
            <a href="{% url 'productapp:product_detail' product_slug=product.slug %}">{{ product.name }}</a>
            <p>{{ product.description }}</p>
            <div class="product-card-price">Price: ${{ product.price }}</div>
            <p>Stock: {{ product.stock }}</p>
            {% if product.available %}
                <p>Available: Yes</p>
            {% else %}
                <p>Available: No</p>
            {% endif %}
            <a><img src="{{ product.image.url }}" alt="{{ product.name }}"></a>
        </div>
    {% endfor %}
{% endblock %}


{% for product in products %}
    <div class="product-card1">
        <a href="{% url 'productapp:product_detail' product_slug=product.slug %}">{{ product.name }}</a>
        <p>{{ product.description }}</p>
        <div class="product-card-price1">Price: ${{ product.price }}</div>
        <div class="product-card-stock1">Stock: {{ product.stock }}</div>
        {% if product.available %}
            <p>Available: Yes</p>
        {% else %}
            <p>Available: No</p>
        {% endif %}
        <!-- Correct the image tag -->
        <img src="{{ product.image.url }}" alt="{{ product.name }}">
    </div>
{% endfor %}
</body>
</html>